name: rushd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  just_audio: ^0.9.30
  audio_video_progress_bar: ^0.11.0
  subtitle: ^0.1.0-beta.3
  get: 4.6.5
  flutter: 
    sdk: flutter
  just_audio_background: ^0.0.1-beta.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

